name: Python Code Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f apps/backend/requirements.txt ]; then pip install -r apps/backend/requirements.txt; fi
        if [ -f apps/backend/requirements-dev.txt ]; then pip install -r apps/backend/requirements-dev.txt; fi

    - name: Check formatting with Black
      run: |
        black --check apps/backend

    - name: Check imports with isort
      run: |
        isort --check-only --profile black apps/backend

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 apps/backend --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 apps/backend --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Type check with mypy
      run: |
        mypy apps/backend
